// <auto-generated />
namespace Beemonitor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class linkasid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(linkasid));
        
        string IMigrationMetadata.Id
        {
            get { return "201709161950340_linkasid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
